version: 2
jobs:
  api-lint:
    docker:
      - image: circleci/openjdk:8-jdk
        working_directory: ~/heracles-api
    steps:
      - checkout

      - run:
          name: cd heracles-api directory
          command: cd heracles-api/

      # run linting!
      - run:
          name: run linting
          command: ./bin/lint.sh

  api-unit-test:
    docker:
      - image: circleci/openjdk:8-jdk
        working_directory: ~/heracles-api
    steps:
      - checkout

      - run:
          name: cd heracles-api directory
          command: cd heracles-api/

      # run linting!
      - run:
          name: run linting
          command: ./bin/unit-test.sh

workflows:
  version: 2
  commit:
    jobs:
      - api-lint
      - api-unit-test
