version: 2
jobs:
  api-lint:
    docker:
      - image: circleci/openjdk:11-jdk
        working_directory: ~/heracles-api
    steps:
      - checkout

      # copy code to cwd
      - run:
          name: copy heracles-api to cwd
          command: ls

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "heracles-api/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "heracles-api/build.gradle" }}

      # run linting!
      - run:
          name: run linting
          command: ./bin/lint.sh

  api-unit-test:
    docker:
      - image: circleci/openjdk:8-jdk
        working_directory: ~/heracles-api
    steps:
      - checkout

      # copy code to cwd
      - run:
          name: copy heracles-api to cwd
          command: cp -r heracles-api/ .

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "heracles-api/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "heracles-api/build.gradle" }}

      - run:
          name: run linting
          command: ./bin/unit-test.sh

  api-integration-test:
    docker:
      - image: circleci/openjdk:8-jdk
        working_directory: ~/heracles-api
    steps:
      - checkout

      # copy code to cwd
      - run:
          name: copy heracles-api to cwd
          command: cp -r heracles-api/ .

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "heracles-api/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "heracles-api/build.gradle" }}

      - run:
          name: run linting
          command: ./bin/integration-test.sh

  ui-lint:
    docker:
      - image: circleci/node:10.16.3
        working_directory: ~/heracles-ui
    steps:
      - checkout

      # copy code to cwd
      - run:
          name: copy heracles-api to cwd
          command: cp -r heracles-ui/ .

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "heracles-ui/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "heracles-ui/package.json" }}

      # run linting!
      - run:
          name: run linting
          command: ./bin/lint.sh

  ui-unit-test:
    docker:
      - image: circleci/node:10.16.3
        working_directory: ~/heracles-ui
    steps:
      - checkout

      # copy code to cwd
      - run:
          name: copy heracles-api to cwd
          command: cp -r heracles-ui/ .

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "heracles-ui/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "heracles-ui/package.json" }}

      # run linting!
      - run:
          name: run linting
          command: ./bin/unit-test.sh

  end-to-end-test:
    docker:
      - image: circleci/node:10.16.3
        working_directory: ~/heracles-ui
    steps:
      - checkout

      # copy code to cwd
      - run:
          name: copy heracles-api to cwd
          command: cp -r heracles-ui/ .

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "heracles-ui/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "heracles-ui/package.json" }}

      # run linting!
      - run:
          name: run linting
          command: ./bin/e2e-test.sh

workflows:
  version: 2
  commit:
    jobs:
      - api-lint
      - api-unit-test
      - api-integration-test
      - ui-lint
      - ui-unit-test
      - end-to-end-test
