swagger: "2.0"
definitions:
  ApiErrorResponse:
    type: object
    properties:
      header:
        $ref: "./common_1.yml#/definitions/Header"
      result:
        type: string
    required:
      - header
